//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocBookSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int MusicId { get; set; }
        public int SingerId { get; set; }
        public int AlbumId { get; set; }
        public int AuthorId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public System.DateTime PublishTime { get; set; }
        public int Price { get; set; }
        public string Tags { get; set; }
        public string Size { get; set; }
        public string Duration { get; set; }
        public string Quality { get; set; }
        public Nullable<int> ViewNumber { get; set; }
        public string Link { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
