//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocBookSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Music
    {
        public int MusicId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public System.DateTime PublishTime { get; set; }
        public int Price { get; set; }
        public string Tags { get; set; }
        public string Size { get; set; }
        public string Duration { get; set; }
        public string Quality { get; set; }
        public Nullable<int> ViewNumber { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Description { get; set; }
        public string MusicCategoryName { get; set; }
        public string SingerName { get; set; }
        public int Age { get; set; }
        public string Country { get; set; }
        public string Company { get; set; }
        public string SingerDescription { get; set; }
        public Nullable<bool> SingerActive { get; set; }
        public bool MusicCategoryActive { get; set; }
        public bool IsActive { get; set; }
        public string AlbumName { get; set; }
        public string Image { get; set; }
        public string AlbumDescription { get; set; }
        public Nullable<System.DateTime> AlbumPublishTime { get; set; }
        public Nullable<bool> AlbumActive { get; set; }
        public string MusicAuthorsName { get; set; }
    }
}
